[general]
import = [
  "~/.config/alacritty/themes/themes/tokyo_night.toml"
]
#
[window]
padding = { x = 4, y = 2} # ターミナルの上下左右の余白 
opacity = 0.7
blur = true
option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"
size = 15

#
# [terminal]
# shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux"] }
